name: Add Icon

on:
  repository_dispatch:
    types: addIcon
  push:
    branches:
      - main

jobs:
  addIcon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: cd src/scripts && npm install && npm run build && npm run start
    timeout-minutes: 5
