name: Add Icon

on:
  repository_dispatch:
    types: addIcon

jobs:
  addIcon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: cd src/scripts
      - name: Install dependencies
        run: npm install
      - name: Build and run
        run: npm run build && npm run start
    timeout-minutes: 5
